import type { Translate } from '../domain/index.js';

const messages: Record<string, string> = {
  'workspace.loading': 'Loading repository…', 'workspace.retry': 'Retry', 'workspace.changes': 'Changes', 'workspace.history': 'History', 'workspace.historyAuto': 'Auto', 'workspace.historyAll': 'All refs', 'workspace.historyManual': 'Manual refs', 'workspace.historyManualRefs': 'Comma-separated refs', 'workspace.apply': 'Apply', 'workspace.commit': 'Commit', 'workspace.refresh': 'Refresh', 'workspace.compare': 'Compare', 'workspace.loadMore': 'Load more', 'workspace.noChanges': 'Working tree is clean', 'workspace.noHistory': 'No commits found', 'workspace.stage': 'Stage', 'workspace.unstage': 'Unstage', 'workspace.discard': 'Discard', 'workspace.commitMessage': 'Commit message', 'workspace.commitAction': 'Commit staged changes', 'workspace.staged': 'Staged', 'workspace.unstaged': 'Unstaged', 'workspace.files': 'Files', 'workspace.parent': 'Parent', 'workspace.rootCommit': 'Root commit', 'workspace.close': 'Close', 'workspace.cancel': 'Cancel', 'workspace.confirm': 'Confirm', 'workspace.success': 'Git operation completed', 'workspace.pendingJob': 'Git operation is still running', 'workspace.binary': 'Binary file cannot be displayed', 'workspace.truncated': 'Diff is truncated', 'workspace.copyHash': 'Copy commit hash', 'workspace.openUrl': 'Open remote', 'workspace.recovery': 'Recovery', 'workspace.continue': 'Continue', 'workspace.abort': 'Abort', 'workspace.sync': 'Sync', 'workspace.fetch': 'Fetch', 'workspace.pull': 'Pull', 'workspace.push': 'Push', 'workspace.branch': 'Branch', 'workspace.tag': 'Tag', 'workspace.stash': 'Stash', 'workspace.working': 'Working tree', 'workspace.hunkStage': 'Stage hunk', 'workspace.hunkUnstage': 'Unstage hunk', 'workspace.hunkDiscard': 'Discard hunk', 'workspace.error': 'Git operation failed', 'workspace.tabs': 'Open diffs',
  'gitActions.label': 'Git actions', 'gitActions.branches': 'Branches', 'gitActions.branch': 'Branch', 'gitActions.selectBranch': 'Select a branch', 'gitActions.createBranch': 'Create branch', 'gitActions.checkout': 'Checkout', 'gitActions.checkoutBranch': 'Checkout branch', 'gitActions.rename': 'Rename', 'gitActions.renameBranch': 'Rename branch', 'gitActions.delete': 'Delete', 'gitActions.deleteBranch': 'Delete branch', 'gitActions.merge': 'Merge', 'gitActions.rebase': 'Rebase', 'gitActions.tags': 'Tags', 'gitActions.tag': 'Tag', 'gitActions.selectTag': 'Select a tag', 'gitActions.createTag': 'Create tag', 'gitActions.deleteTag': 'Delete tag', 'gitActions.commit': 'Selected commit', 'gitActions.checkoutDetached': 'Checkout detached', 'gitActions.cherryPick': 'Cherry-pick', 'gitActions.revert': 'Revert', 'gitActions.resetSoft': 'Reset soft', 'gitActions.resetMixed': 'Reset mixed', 'gitActions.resetHard': 'Reset hard', 'gitActions.stashes': 'Stashes', 'gitActions.stash': 'Stash', 'gitActions.selectStash': 'Select a stash', 'gitActions.stashSave': 'Save stash', 'gitActions.stashApply': 'Apply stash', 'gitActions.stashPop': 'Pop stash', 'gitActions.stashDrop': 'Drop stash', 'gitActions.recovery': 'Recovery', 'gitActions.continue': 'Continue', 'gitActions.abort': 'Abort', 'gitActions.stashMessage': 'Stash message', 'gitActions.includeUntracked': 'Include untracked files', 'gitActions.tagName': 'Tag name', 'gitActions.branchName': 'Branch name', 'gitActions.cancel': 'Cancel', 'gitActions.submit': 'Continue',
  'workspace.selectParent': 'Select parent commit for diff', 'workspace.parentOption': 'Parent {number} ({hash})', 'hover.copyHash': 'Copy commit hash', 'hover.openGitGraph': 'Open in Git Graph',
  'compact.loading': 'Loading graph…', 'compact.error': 'Unable to load graph.', 'compact.empty': 'No commits found.', 'hover.error': 'Unable to load commit.', 'hover.unavailable': 'Commit unavailable.',
  'status.historyMode': 'History mode', 'status.mode.auto': 'Auto', 'status.mode.all': 'All', 'status.mode.manual': 'Manual', 'status.refresh': 'Refresh', 'status.refs': 'Branches', 'status.loading': 'Loading commits…', 'status.error': 'Unable to load commits.', 'status.empty': 'No commits found.', 'status.noDirectory': 'Open a workspace to see commits.', 'status.openCommit': 'Open commit {subject} by {author}', 'status.copyHash': 'Copy hash', 'status.openDiff': 'Open diff', 'status.openError': 'Could not open the diff.', 'status.copyError': 'Could not copy the commit hash.', 'status.preferencesReadError': 'Could not load saved history preferences.', 'status.preferencesSaveError': 'Could not save history preferences.',
};
export const defaultT: Translate = (key, values) => (messages[key] ?? key).replace(/\{(\w+)\}/g, (_, name: string) => String(values?.[name] ?? `{${name}}`));
