name: Verify plugin
on:
  pull_request:
permissions: { contents: read }
jobs:
  verify:
    uses: ./.github/workflows/build-test-host.yml
    with:
      source_sha: ${{ github.sha }}
    permissions: { contents: read }
